version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - 8501:8501
    env_file:
      - .env
    depends_on:
      - backend
    environment:
      - BACKEND_HOST=http://backend:8000
    volumes:
      - ./frontend:/frontend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./backend:/backend
    networks:
      - app-network    
  
  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'dev-db'
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-data:/var/lib/mysql    
    ports:
      - 3306:3306
    networks:
      - app-network
   
volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge